# Loosely based upon:
#   https://github.com/actions/starter-workflows/blob/main/ci/php.yml

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.2, 7.3, 7.4, 8.0, 8.1]
        laravel-version: [6.*, 7.*, 8.*, 9.*]
        include:
          - laravel-version: 6.*
            testbench: 4.*
          - laravel-version: 7.*
            testbench: 5.*
          - laravel-version: 8.*
            testbench: 6.*
          - laravel-version: 9.*
            testbench: 7.*
        exclude:
          - laravel-version: 8.*
            php-version: 7.2
          - laravel-version: 9.*
            php-version: 7.2
          - laravel-version: 9.*
            php-version: 7.3
          - laravel-version: 9.*
            php-version: 7.4

    name: P${{ matrix.php-version }} - L${{ matrix.laravel-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel-version }}" --no-interaction --no-update
          composer require --dev "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer install --prefer-dist --no-progress

      # the test script is configured in composer.json.
      # see: https://getcomposer.org/doc/articles/scripts.md
      - name: Run test suite
        run: composer run-script test
